countryAbb = {
    "united kingdom": ["uk", "england", "great britain", "gb", "scotland", "wales", "northern ireland", "london"],
    "united states": ["usa", "us", "u.s.", "u.s.a.", "america", "united states of america", "los angeles", "san francisco"],
    "russian federation": ["russia", "russian empire", "ussr", "soviet union"],
    "korea, republic of": ["korea", "south korea", "republic of korea"],
    "korea, democratic people's republic of": ["north korea", "dprk"],
    "china": ["people's republic of china", "prc", "mainland china"],
    "taiwan": ["republic of china", "roc"],
    "iran, islamic republic of": ["iran", "persia"],
    "ireland": "dublin",
    "india": ["hyderabad"],
    "viet nam": ["vietnam"],
    "czechia": ["czech republic", "czech"],
    "slovakia": ["slovak republic", "slovak"],
    "méxico": "mexico",
    "myanmar": ["burma"],
    "palestine, state of": ["palestine", "palestinian territories", "west bank", "gaza"],
    "venezuela, bolivarian republic of": ["venezuela"],
    "moldova, republic of": ["moldova"],
    "tanzania, united republic of": ["tanzania"],
    "lao people's democratic republic": ["laos"],
    "syrian arab republic": ["syria"],
    "bolivia, plurinational state of": ["bolivia"],
    "north macedonia": ["macedonia", "macedonia, the former yugoslav republic of"],
    "côte d’ivoire": ["ivory coast", "cote d'ivoire"],
    "congo, the democratic republic of the": ["drc", "democratic republic of the congo", "zaire"],
    "congo": ["republic of the congo", "congo-brazzaville"],
    "gambia, the": ["gambia"],
    "bahamas, the": ["bahamas"],
    "netherlands": ["holland"],
    "eswatini": ["swaziland"],
    "timor-leste": ["east timor"],
    "holy see": ["vatican", "vatican city"],
    "brunei darussalam": ["brunei"],
    "united arab emirates": ["uae"],
    "sudan": ["north sudan"],
    "south sudan": ["republic of south sudan"],
    "spain": ["barcelona"],
    "micronesia, federated states of": ["micronesia"],
    "bosnia and herzegovina": ["bosnia", "bih"],
    "dominican republic": ["dominicana"],
    "guinea-bissau": ["guinea bissau"],
    "equatorial guinea": ["guinea ecuatorial"],
    "trinidad and tobago": ["tnt"],
    "são tomé and príncipe": ["sao tome", "sao tome and principe"],
    "united republic of tanzania": ["tanzania"],
    "marshall islands": ["rmi"],
    "saint kitts and nevis": ["stkitts"],
    "saint lucia": ["st lucia"],
    "saint vincent and the grenadines": ["st vincent"],
    "antigua and barbuda": ["antigua"],
    "central african republic": ["car"],
    "democratic republic of the congo": ["drc", "dr congo", "zaire"],
    "republic of the congo": ["congo-brazzaville"],
    "libyan arab jamahiriya": ["libya"],
    "myanmar, burma": ["myanmar", "burma"],
    "perú": "peru",
}
